version: '2'
services:

    app:
        build: ./
        volumes:
            - ./:/var/www/html/
        links:
            - db
        environment:
            ENABLE_ENV_FILE: 1
            ENABLE_LOCALCONF: 1
            API_TOKEN: "c9575fee817180194a64253fd63cd4dddd0f8220"


        # For Apache based image:
        # ports:
            # - "8080:80"

        # For FPM/HHVM based image:
        expose:
           - "9000"

        # Autostart at boottime
        restart: always

        # Send log output to syslog
        #logging:
        #    driver: "syslog"
        #    options:
        #        tag: "docker-web"

    # For FPM/HHVM based image:
    nginx:
       build: ./nginx
       restart: always
       ports:
           - "8081:80"
       links:
           - app
       volumes_from:
           - app

    db:
        image: mysql:5.6
        ports:
            - "3307:3306"
        expose:
            - "3307"
        environment:
            MYSQL_ROOT_PASSWORD: secret-root
            MYSQL_DATABASE: web
            MYSQL_USER: web
            MYSQL_PASSWORD: web

        # Autostart at boottime
        #restart: always

